### ISSUE TITLE
add button( detail caller)

### ISSUE THREAD

**Issue by lammh** [tipichris/callPopPy#1]
Hi, thank's for a script
how i can add button to url in self.popup.show!

**Comment by tipichris** [comment]
That will depend on whether you are using pynotify or gtkPopupNotify. You will need to look at the documentation for those libraries. TBH, I'm not sure that you can add a button. With pynotify I don't think the underlying operating system mechanism supports buttons (NotifyOSD on Ubuntu). You may have to change things to use an alert box instead.

**Comment by lammh** [comment]
Ok think's for your response! 
May be I will change the Notif method
